name: pak

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
      - ci
  workflow_dispatch:
      
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Alpakitnt
        run: |
          from subprocess import run
          from json impord load
          secrets = load("secrets.json")
          uproject = f'"{secrets['PROJDIR']}\\FactoryGame.uproject"'
          cli = [
            f'"{secrets["UE4DIR"]}\\Build\\BatchFiles\\RunUAT.bat"',
            f'-ScriptsForProject={uproject}',
            'PackagePlugin',
            f'-Project={uproject}',
            '-PluginName="AFSuperNobs"',
            '-CopyToGameDir',
            '-GameDir="{secrets["GAMEDIR"]}"'
          ]
          run(cli)
          exit()
        shell: python
