name: pak

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
      - ci
  workflow_dispatch:
      
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Alpakitnt
        run: ${engineLocation}\Build\BatchFiles\RunUAT.bat -ScriptsForProject="${projectLocation}\FactoryGame.uproject" PackagePlugin -Project="${projectLocation}\FactoryGame.uproject" -PluginName="AFSuperNobs" -CopyToGameDir -GameDir="{gameLocation}"
    
