name: pak and push

on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Alpakit
        run: |
          from subprocess import run
          from json import load
          with open('secrets.env') as env:
            secrets = load(env)
          uproject = f'"{secrets["PROJDIR"]}\\FactoryGame.uproject"'
          cli = [
            f'"{secrets["UE4DIR"]}\\Build\\BatchFiles\\RunUAT.bat"',
            f'-ScriptsForProject="{uproject}"',
            'PackagePlugin',
            f'-Project="{uproject}"',
            '-PluginName="AFSuperNobs"',
          ]
          run(cli)
          exit()
        shell: python

      - name: Optimize and write zip
        run: |
          from zopfli import ZipFile
          from zipfile import ZIP_DEFLATED
          from json import load
          with open('secrets.env') as env:
            secrets = load(env)
          modzip = secrets['PROJDIR'] + '\\Saved\\ArchivedPlugins\\WindowsNoEditor\\AFSuperNobs.zip'
          with (ZipFile(modzip) as zr, ZipFile('tmp', 'w', ZIP_DEFLATED, True) as zw):
            il = zr.infolist()
            for i in range(0, len(il)):
              zi = il[i]
              print('Processing', zi.filename, i+1, '/', len(il))
              zw.writestr(zi, zr.read(zi))
        shell: python
        
      - name: Release zip
        uses: actions/upload-artifact@v2
        with:
          name: AFSuperNobs
          path: tmp
          
