name: pak and push

on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
      
jobs:
  build:
    runs-on: windows-latest
    env:
      MOD_REF: ${{ github.event.repository.name }}
    steps:
    
      - name: Print mod reference
        run: echo ${{ env.MOD_REF }}
    
      - name: Alpakit
        run: |
          $uproject=@"
          "${{ secrets.PROJDIR }}/FactoryGame.uproject"
          "@
          $run=@"
          "${{ secrets.UE4DIR }}/Engine/Build/BatchFiles/RunUAT.bat" -ScriptsForProject=$uproject PackagePlugin -Project=$uproject -PluginName="${{ env.MOD_REF }}"
          "@
          iex "& $run"

      - name: Optimize and write zipped mod contents
        run: |
          from zopfli import ZipFile
          from zipfile import ZIP_DEFLATED
          modzip = '${{ secrets.PROJDIR }}/Saved/ArchivedPlugins/WindowsNoEditor/${{ env.MOD_REF }}.zip'
          with (ZipFile(modzip) as zr, ZipFile('${{ env.MOD_REF }}.zip', 'w', ZIP_DEFLATED, True) as zw):
            il = zr.infolist()
            for i in range(0, len(il)):
              zi = il[i]
              print('Processing', zi.filename, i+1, '/', len(il), end='... ')
              zw.writestr(zi, zr.read(zi))
              print('done!')
        shell: python
      
      - name: Release zipped mod contents
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release"
          files: ${{ env.MOD_REF }}.zip
