name: pak

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
      
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Alpakit
        run: |
          from subprocess import run
          from json import load
          secrets = load('secrets.env')
          uproject = f'"{secrets["PROJDIR"]}\\FactoryGame.uproject"'
          cli = [
            f'"{secrets["UE4DIR"]}\\Build\\BatchFiles\\RunUAT.bat"',
            f'-ScriptsForProject="{uproject}"',
            'PackagePlugin',
            f'-Project="{uproject}"',
            '-PluginName="AFSuperNobs"',
          ]
          run(cli)
          exit()
        shell: python

      - name: Optimize and release zip
        run: |
          from zopfli import ZipFile
          from zipfile import ZIP_DEFLATED
          from json import load
          secrets = load('secrets.env')
          modzip = secrets['PROJDIR'] + '\\Saved\\ArchivedPlugins\\WindowsNoEditor\\AFSuperNobs.zip'
          with (ZipFile(modzip) as zr, ZipFile('tmp', 'w', ZIP_DEFLATED, True) as zw):
            il = zr.infolist()
            for i in range(0, len(il)):
              zi = il[i]
              print('Processing', zi.filename, i+1, '/', len(il))
              zw.writestr(zi, zr.read(zi))
        shell: python
          
